### ISSUE TITLE
data-template download

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/whattemplatemaker#15] opened 2022-02-15 13:23 UTC
When downloading the finished data-template, the resulting Excel file has all notes open by default (see below). Can that be changed to having them all closed by default?

![image](https://user-images.githubusercontent.com/3445092/154070613-79531cec-7e4d-4421-9dac-5ff27a5b38a5.png)

**Comment by jeffreyhanson** [comment] 2022-02-15 21:35
Oh - I noticed the LibreOffice Calc does this on my Linux computer, but assumed that wouldn't be thse case for Excel. I'll take a look into this.

**Comment by jeffreyhanson** [comment] 2022-02-22 03:31
Closing this because it is a duplicate of #26.

**Comment by jeffreyhanson** [comment] 2022-02-22 03:44
Upon further inspection, it would appear that the issue is due to how comments are created in the whatdataio repo. So I'll re-open this issue so we can keep track of when this issue is addred for this repo.

**Closed** 2022-02-22 03:46 UTC
Labels: bug, high priority
