### ISSUE TITLE
long id on site details kills it - cannot advance

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#21] opened 2022-02-17 16:58 UTC
I seem to remember you were aware of this. I couldn't find an error message.

**Comment by jeffreyhanson** [comment] 2022-02-20 20:58
Thanks for reporting this! I'm having trouble reproducing this error. When the user inputs a long site id then the app should display this message: "Oops: Each value in the \"id\" column must be shorter than 20 characters in length". Do you remember what the site id was that crashed the app? Also, was the site id supplied after drawing the site boundaries, or when just entering into the table?

**Comment by jeffreyhanson** [comment] 2022-02-22 04:12
@josephrbennett, I think this issue might be due to the same underlying bug as described in https://github.com/NCC-CNC/whattemplatemaker/issues/23. Did you encounter this issue when trying to download the data, or at some other step?

**Comment by jeffreyhanson** [comment] 2022-03-01 04:04
Per b7e3fbb4fb17b9d3653ebf208424b6e84f24c2b2, it is now impossible for the user to enter really long id values (the table won't accept them if you press enter), so I'll close this issue now. Please feel free to re-open this issue if you run into certain site id values killing the application.

**Closed by jeffreyhanson** 2022-03-01 04:04 UTC
Labels: bug, high priority
